"""empty message

Revision ID: adfe32ad18aa
Revises: 9d28ee233d07
Create Date: 2019-02-11 16:48:31.718132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfe32ad18aa'
down_revision = '9d28ee233d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('email', sa.String(length=40), nullable=True))
    op.add_column('post', sa.Column('gender', sa.String(length=40), nullable=True))
    op.add_column('post', sa.Column('name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'name')
    op.drop_column('post', 'gender')
    op.drop_column('post', 'email')
    # ### end Alembic commands ###
